services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storyteller
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    # can be set in .env also
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: 123

  db:
    image: mysql:8.0
    container_name: storyteller_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root_password
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: storyteller_pma
    depends_on:
      - db
    ports:
      - "1337:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  mysql_data: